import { NextRequest, NextResponse } from 'next/server';
import { promises as fs } from 'fs';
import path from 'path';

const SETTINGS_FILE = path.join(process.cwd(), '..', 'settings.json');

interface EnvConfig {
  googleAiApiKey: string;
  agentToken: string;
  agentAdkModel: string;
  agentAdkEnabled: boolean;
  serverPort: string;
  agentWorkingDir: string;
  agentDefaultShell: string;
  agentMaxConcurrent: string;
  setupComplete: boolean;
}

const defaultConfig: EnvConfig = {
  googleAiApiKey: '',
  agentToken: '1234',
  agentAdkModel: 'gemini-2.0-flash',
  agentAdkEnabled: true,
  serverPort: '8090',
  agentWorkingDir: '/tmp',
  agentDefaultShell: '/bin/bash',
  agentMaxConcurrent: '5',
  setupComplete: false,
};

async function readSettings(): Promise<EnvConfig> {
  try {
    const data = await fs.readFile(SETTINGS_FILE, 'utf-8');
    return { ...defaultConfig, ...JSON.parse(data) };
  } catch {
    return defaultConfig;
  }
}

async function writeSettings(config: EnvConfig): Promise<void> {
  await fs.writeFile(SETTINGS_FILE, JSON.stringify(config, null, 2));
}

async function writeEnvFile(config: EnvConfig): Promise<void> {
  const envPath = path.join(process.cwd(), '..', '.env');

  const envContent = `# GRIPHOOK Configuration
# Generated by Settings UI

# Google AI API Key (required for AI chat)
GOOGLE_AI_API_KEY=${config.googleAiApiKey}

# Agent Authentication Token
AGENT_TOKEN=${config.agentToken}

# AI Configuration
AGENT_ADK_MODEL=${config.agentAdkModel}
AGENT_ADK_ENABLED=${config.agentAdkEnabled}

# Server Configuration
SERVER_PORT=${config.serverPort}
AGENT_WORKING_DIR=${config.agentWorkingDir}
AGENT_DEFAULT_SHELL=${config.agentDefaultShell}
AGENT_MAX_CONCURRENT=${config.agentMaxConcurrent}
`;

  await fs.writeFile(envPath, envContent);
}

export async function GET() {
  try {
    const config = await readSettings();
    // Mask the API key for security
    return NextResponse.json({
      ...config,
      googleAiApiKey: config.googleAiApiKey ? '•'.repeat(20) + config.googleAiApiKey.slice(-4) : '',
    });
  } catch (error) {
    console.error('Failed to read settings:', error);
    return NextResponse.json({ error: 'Failed to read settings' }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const currentConfig = await readSettings();

    // If the API key is masked, keep the original
    const newConfig: EnvConfig = {
      googleAiApiKey: body.googleAiApiKey?.startsWith('•')
        ? currentConfig.googleAiApiKey
        : (body.googleAiApiKey ?? currentConfig.googleAiApiKey ?? ''),
      agentToken: body.agentToken ?? currentConfig.agentToken ?? defaultConfig.agentToken,
      agentAdkModel: body.agentAdkModel ?? currentConfig.agentAdkModel ?? defaultConfig.agentAdkModel,
      agentAdkEnabled: body.agentAdkEnabled ?? currentConfig.agentAdkEnabled ?? defaultConfig.agentAdkEnabled,
      serverPort: body.serverPort ?? currentConfig.serverPort ?? defaultConfig.serverPort,
      agentWorkingDir: body.agentWorkingDir ?? currentConfig.agentWorkingDir ?? defaultConfig.agentWorkingDir,
      agentDefaultShell: body.agentDefaultShell ?? currentConfig.agentDefaultShell ?? defaultConfig.agentDefaultShell,
      agentMaxConcurrent: body.agentMaxConcurrent ?? currentConfig.agentMaxConcurrent ?? defaultConfig.agentMaxConcurrent,
      setupComplete: body.setupComplete ?? currentConfig.setupComplete ?? defaultConfig.setupComplete,
    };

    // Save to both settings.json and .env
    await writeSettings(newConfig);
    await writeEnvFile(newConfig);

    return NextResponse.json({
      success: true,
      message: 'Settings saved. Restart the backend for changes to take effect.'
    });
  } catch (error) {
    console.error('Failed to save settings:', error);
    return NextResponse.json({ error: 'Failed to save settings' }, { status: 500 });
  }
}
